num1=float(input("Enter first number: "))
num2=float(input("Enter second number: "))
print("Addition:",num1+num2)
print("substraction:",num1-num2)
print("Multiplication:",num1*num2)
print("Division:",num1/num2)
print("Modulus:",num1%num2)
print("Floor Division:",num1//num2)
print("Power:",num1**num2)
